[package]
name = "bevyterm"
authors = ["MichaÃ«l Mendes <michael.mendes1@gmail.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.0"
crossterm = "0.26.1"
